M48
; DRILL file {KiCad 9.0.6} date 2026-06-17T22:07:34-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-17T22:07:34-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X5.0043Y-2.201
X5.2319Y-2.201
T2
X4.5728Y-2.1555
X4.8406Y-2.1555
M30
